#!/bin/sh
#
# Copyright (C) 2026 iris-GmbH infrared & intelligent sensors
#
# SPDX-License-Identifier: MIT

_FILE_FITIMAGE="fitImage.signed"
_FILE_ROOTFS_GZ="rootfs.ext4.verity.gz"
_FILE_ROOTFS_HASHDEVICE="rootfs.ext4.hashdevice"
_FILE_ROOTFS_ROOTHASH="rootfs.ext4.roothash"
_FILE_ROOTFS_ROOTHASH_SIGNATURE="rootfs.ext4.roothash.signature"

_LVM_LABEL="hydralvm"

_MNT_KEYSTORE="/mnt/keystore"
_MNT_USERDATA="/mnt/hydra"
_MNT_DATASTORE="/mnt/datastore"
_MNT_PROVISIONING="/mnt/provisioning"

_ROOTHASH_PUBKEY="/etc/iris/signing/roothash-public-key.pem"

fail() {
    echo "$(date): ${*}"
    # TODO - reboot here?
    # exit 1 will cause kernel to panic as we're PID 1
    exit 1
}

copy_fitimage() {
    partition="$1"
    fitimage="$2"

    mount -t ext4 -o rw "${partition}" /tmp/boot
    cp "${fitimage}" /tmp/boot/fitImage.signed.deploy
    umount /tmp/boot
}

finalize_fitimage() {
    partition="$1"

    mount -t ext4 -o rw "${partition}" /tmp/boot
    mv /tmp/boot/fitImage.signed.deploy /tmp/boot/fitImage.signed
    umount /tmp/boot
}

write_verity_artifacts() {
    label="$1"

    cp "/tmp/provisioning/${_FILE_ROOTFS_HASHDEVICE}" "${_MNT_KEYSTORE}/verity/${label}.hashdevice"
    cp "/tmp/provisioning/${_FILE_ROOTFS_ROOTHASH}" "${_MNT_KEYSTORE}/verity/${label}.roothash"
    cp "/tmp/provisioning/${_FILE_ROOTFS_ROOTHASH_SIGNATURE}" "${_MNT_KEYSTORE}/verity/${label}.roothash.signature"
}

prepare_sdcard() {
    # Create the same state as sd-preparation with artifacts from ..p4
    # Copy all artifacts from p4 into tmpfs
    mount -t ext4 -o ro "${DEV}p4" /tmp/mnt
    cp -avx /tmp/mnt/. /tmp/provisioning
    umount /tmp/mnt

    # Extend p4, create LVM
    parted -s "${DEV}" resizepart 4 100%
    partprobe "${DEV}"

    pvcreate -ff -y "${LVMDEV}"
    vgcreate --devices "${LVMDEV}" "${_LVM_LABEL}" "${LVMDEV}"

    rootfs_bytes=$(tail -c 4 "/tmp/provisioning/${_FILE_ROOTFS_GZ}" | od -An -tu4 | xargs)
    # no need for alignment as verity images are always a multiple of 512 in size
    lvcreate -y --devices "${LVMDEV}" -n "rootfs_a" -L "${rootfs_bytes}B" "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "rootfs_b" -L "${rootfs_bytes}B" "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "userdata_a" -L 512MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "userdata_b" -L 512MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "keystore" -L 128MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "provisioning" -L 128MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "datastore" -L 128MB "${_LVM_LABEL}"

    lvcreate -y --devices "${LVMDEV}" -n "pvsn_rootfs" -L "${rootfs_bytes}B" "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "pvsn_userdata" -L 512MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "pvsn_provisioning" -L 128MB "${_LVM_LABEL}"
    lvcreate -y --devices "${LVMDEV}" -n "pvsn_datastore" -L 128MB "${_LVM_LABEL}"

    vgchange -a y --devices "${LVMDEV}"
    vgmknodes --devices "${LVMDEV}"

    # Format and mount keystore volume
    mkfs.ext4 -qF "${keystore_dev}"
    mount "${keystore_dev}" "${_MNT_KEYSTORE}"
    mkdir -p "${_MNT_KEYSTORE}/caam" "${_MNT_KEYSTORE}/verity"

    # Copy rootfs artifacts to keystore (skip rootfs_b)
    write_verity_artifacts "rootfs_a"

    umount "${_MNT_KEYSTORE}"

    # write un-encrypted rootfs_a
    zcat "/tmp/provisioning/${_FILE_ROOTFS_GZ}" > "/dev/mapper/${_LVM_LABEL}-pvsn_rootfs"
    sync

    # prepare ext4 volumes
    mkfs.ext4 -qF "/dev/mapper/${_LVM_LABEL}-pvsn_userdata"
    mkfs.ext4 -qF "/dev/mapper/${_LVM_LABEL}-pvsn_provisioning"
    mkfs.ext4 -qF "/dev/mapper/${_LVM_LABEL}-pvsn_datastore"

    # Put signed fitimage into boot_a and boot_b
    copy_fitimage "${DEV}p2" "/tmp/provisioning/${_FILE_FITIMAGE}"
    copy_fitimage "${DEV}p1" "/tmp/provisioning/${_FILE_FITIMAGE}"
}

verify_mount_rootfs() {
    label="$1" # LVM volume name
    verity="$2" # "rootfs_a" or "rootfs_b" hashes
    target="$3" # mount target

    volume="/dev/mapper/${_LVM_LABEL}-${label}"

    verity_label="verity-${_LVM_LABEL}-${verity}"
    verity_dev="/dev/mapper/${verity_label}"

    verity_roothash="${_MNT_KEYSTORE}/verity/${verity}.roothash"
    verity_signature="${_MNT_KEYSTORE}/verity/${verity}.roothash.signature"
    verity_hashdevice="${_MNT_KEYSTORE}/verity/${verity}.hashdevice"

    if ! /usr/bin/openssl dgst -sha256 -verify "${_ROOTHASH_PUBKEY}" -signature "${verity_signature}" "${verity_roothash}"
    then
        fail "Root hash signature invalid"
    fi

    veritysetup open --root-hash-file="${verity_roothash}" "${volume}" "${verity_label}" "${verity_hashdevice}"
    mount -t ext4 -o ro "${verity_dev}" "${target}"
}

hiposprovisioning_enabled() {
    return 0
}

hiposprovisioning_run() {
    LVMDEV="${bootparam_root}"
    DEV=${LVMDEV%p[0-9]*}

    . /usr/share/hipos_provisioning_common.sh

    keystore_dev="/dev/mapper/${_LVM_LABEL}-keystore"

    mount -t tmpfs tmp /tmp
    mkdir /tmp/mnt /tmp/provisioning /tmp/boot
    mkdir -p "${_MNT_KEYSTORE}" "${_MNT_DATASTORE}" "${_MNT_PROVISIONING}"

    if ! vgs --devices "${LVMDEV}" "${_LVM_LABEL}" ;
    then
        # this will run when sd-img was used - create the same setup as sd-preparation
        prepare_sdcard
    fi

    # Mount prep-volumes
    mount "${keystore_dev}" "${_MNT_KEYSTORE}"
    verify_mount_rootfs "pvsn_rootfs" "rootfs_a" "${ROOTFS_DIR}"

    mount "/dev/mapper/${_LVM_LABEL}-pvsn_userdata" "${_MNT_USERDATA}"
    mount "/dev/mapper/${_LVM_LABEL}-pvsn_provisioning" "${_MNT_PROVISIONING}"
    mount "/dev/mapper/${_LVM_LABEL}-pvsn_datastore" "${_MNT_DATASTORE}"

    # modify runtime for production need
    # - inject root password
    cp "${ROOTFS_DIR}/etc/shadow" /tmp/etc_shadow
    sed -e "s%^root:[^:]*:%root:${INJECTED_ROOTPASSWORD}:%" -i /tmp/etc_shadow
    mount --bind /tmp/etc_shadow "${ROOTFS_DIR}/etc/shadow"

    # move mounts
    mount --move "${_MNT_USERDATA}" "${ROOTFS_DIR}${_MNT_USERDATA}"
    mount --move "${_MNT_KEYSTORE}" "${ROOTFS_DIR}${_MNT_KEYSTORE}"
    mount --move "${_MNT_DATASTORE}" "${ROOTFS_DIR}${_MNT_DATASTORE}"
    mount --move "${_MNT_PROVISIONING}" "${ROOTFS_DIR}${_MNT_PROVISIONING}"
}
