#!/bin/bash
#
# Copyright (C) 2016-2023 DResearch Fahrzeugelektronik GmbH
#

VERBOSITY=0

if [ "${IFACE}" != "eth0" ] && [ "${IFACE}" != "br0" ]; then
	exit 0
fi

if [ -f "/etc/hipos/hipos-network-setup.sh" ]; then
. /etc/hipos/hipos-network-setup.sh >/dev/null
fi

exit 0
