#!/bin/sh

VERBOSITY=0

if [ -f "/run/udhcpc.$IFACE.pid" ]; then
	/bin/kill -15 `cat /run/udhcpc.$IFACE.pid`
fi

if [ -f "/run/wpa_supplicant.$IFACE.pid" ]; then
        /bin/kill -15 `cat /run/wpa_supplicant.$IFACE.pid`
fi

if [ -f "/run/zeroconf.$IFACE.pid" ]; then
        /bin/kill -15 `cat /run/zeroconf.$IFACE.pid`
fi

if [ -f "/run/avahi-autoipd.$IFACE.pid" ]; then
        /bin/kill -15 `cat /run/avahi-autoipd.$IFACE.pid`
fi

exit 0
