#!/bin/sh

VERBOSITY=0

if [ -f "/var/run/udhcpc.$IFACE.pid" ]; then
	/bin/cat /var/run/udhcpc.$IFACE.pid > /sys/fs/cgroup/systemd/tasks
fi

if [ -f "/var/run/wpa_supplicant.$IFACE.pid" ]; then
	/bin/cat /var/run/wpa_supplicant.$IFACE.pid > /sys/fs/cgroup/systemd/tasks
fi

if [ -f "/var/run/zeroconf.$IFACE.pid" ]; then
        /bin/cat /var/run/zeroconf.$IFACE.pid > /sys/fs/cgroup/systemd/tasks
fi

if [ -f "/var/run/avahi-autoipd.$IFACE.pid" ]; then
        /bin/cat /var/run/avahi-autoipd.$IFACE.pid > /sys/fs/cgroup/systemd/tasks
        /bin/echo $(/bin/ps axf  | /bin/grep "avahi-autoipd" | /bin/grep $IFACE | /bin/grep "callout dispatcher" | /usr/bin/awk '{print $1}') > /sys/fs/cgroup/systemd/tasks | /bin/true
fi

exit 0
