#!/bin/sh

VERBOSITY=0

if [ -f "/var/run/udhcpc.$IFACE.pid" ]; then
	/bin/kill -15 `cat /var/run/udhcpc.$IFACE.pid`
fi

if [ -f "/var/run/wpa_supplicant.$IFACE.pid" ]; then
        /bin/kill -15 `cat /var/run/wpa_supplicant.$IFACE.pid`
fi

exit 0
