#!/bin/sh

lvm_enabled() {
	if ! lvscan --devices "${bootparam_root}" |grep -i -w "inactive" &>/dev/null;then
		return 1
	fi
	return 0
}

lvm_run() {
	lvm pvscan --cache --activate ay --devices "${bootparam_root}"
	udevadm trigger --action=add
}
